In [14]:
import numpy as np
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer,load_iris
from sklearn.model_selection import train_test_split

In [5]:
cancer=load_breast_cancer()
data=cancer.data[:,:]
target=cancer.target

In [6]:
xtrain,xtest,ytrain,ytest=train_test_split(data,target,test_size=0.2,random_state=42)

In [7]:
log_regression=LogisticRegression()

In [8]:
log_regression.fit(xtrain,ytrain)

/home/hardik/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [10]:
predict=log_regression.predict(xtest)

In [15]:
print("confusion_matrix:\n",confusion_matrix(predict,ytest))
print("\naccuracy_score:",accuracy_score(predict,ytest)*100,"%")

confusion_matrix:
 [[39  1]
 [ 4 70]]

accuracy_score: 95.6140350877193 %


In [16]:
#iris dataset


iris=load_iris()
data1=iris.data[:,:]
target1=iris.target

In [17]:
x_train,x_test,y_train,y_test=train_test_split(data1,target1,test_size=0.2,random_state=42)

In [18]:
log_regression.fit(x_train,y_train)

/home/hardik/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/hardik/.local/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [20]:
predict_y=log_regression.predict(x_test)

In [21]:
print("confusion_matrix:\n",confusion_matrix(predict_y,y_test))
print("\naccuracy_score:",accuracy_score(predict_y,y_test)*100,"%")

confusion_matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

accuracy_score: 100.0 %
