In [9]:
import numpy as np
import cv2
import matplotlib.pyplot as plt 
from sklearn.cluster import KMeans

In [26]:
image=cv2.imread("OUTPUTS/MESSI SCRAPING.jpg")

In [27]:
image.shape

(432, 768, 3)

In [28]:
image=cv2.resize(image,(500,500))
image_flat=np.reshape(image,(-1,3))

In [29]:
image_flat.shape

(250000, 3)

In [30]:
km=KMeans(n_clusters=10,init="random")


In [32]:
km.fit(image_flat)

KMeans(algorithm='auto', copy_x=True, init='random', max_iter=300,
    n_clusters=10, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [33]:
cluster=km.predict(image_flat)

In [34]:
print(km.cluster_centers_)

[[ 96.99082421 119.61622666 163.72939472]
 [ 29.17144527  23.92310939  25.48356983]
 [208.59598411 217.24602824 236.67255075]
 [132.99602304 170.4003017  215.16799232]
 [ 57.15910799  55.0850664  111.61237785]
 [ 12.11141092   9.34268578   9.51431641]
 [ 82.6097812   40.83086492  30.31988008]
 [ 67.58993229  47.361937   171.21121578]
 [ 36.08267845  36.86936654  45.92979989]
 [119.0420527   58.06590446  45.68953282]]


In [35]:
print(cluster)

[1 1 1 ... 8 8 8]


In [36]:
image_comp_flat=(km.cluster_centers_)[cluster]

In [37]:
img_comp=np.reshape(image_comp_flat,(500,500,3))

In [38]:
cv2.imwrite("OUTPUTS/image_compressed.jpg",img_comp)

True