In [1]:
#--------------------------Dependices------------------------------------
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding
from keras.preprocessing.text import Tokenizer
from keras.utils import np_utils

Using TensorFlow backend.


In [2]:
# creating my own dataset
data = """ I went down yesterday to the Piraeus with Glaucon the son of Ariston,
that I might offer up my prayers to the goddess (Bendis, the Thracian
Artemis.); and also because I wanted to see in what manner they would
celebrate the festival, which was a new thing. I was delighted with the
procession of the inhabitants; but that of the Thracians was equally,
if not more, beautiful. When we had finished our prayers and viewed the
spectacle, we turned in the direction of the city; and at that instant
Polemarchus the son of Cephalus chanced to catch sight of us from a
distance as we were starting on our way home, and told his servant to
run and bid us wait for him. The servant took hold of me by the cloak
behind, and said: Polemarchus desires you to wait.
Accordingly we went with Polemarchus to his house; and there we found
his brothers Lysias and Euthydemus, and with them Thrasymachus the
Chalcedonian, Charmantides the Paeanian, and Cleitophon the son of
Aristonymus. There too was Cephalus the father of Polemarchus, whom I
had not seen for a long time, and I thought him very much aged. He was
seated on a cushioned chair, and had a garland on his head, for he had
been sacrificing in the court; and there were some other chairs in the
room arranged in a semicircle, upon which we sat down by him. He saluted
me eagerly, and then he said You don't come to see me, Socrates, as often as you ought: If I were
still able to go and see you I would not ask you to come to me. But
at my age I can hardly get to the city, and therefore you should come
oftener to the Piraeus. For let me tell you, that the more the pleasures
of the body fade away, the greater to me is the pleasure and charm
of conversation. Do not then deny my request, but make our house your
resort and keep company with these young men; we are old friends, and
you will be quite at home with us."""

In [3]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([data])
encoded_data=tokenizer.texts_to_sequences([data])[0]

In [4]:
print(encoded_data)

[5, 33, 34, 50, 3, 1, 35, 8, 51, 1, 20, 4, 52, 13, 5, 53, 54, 55, 21, 36, 3, 1, 56, 57, 1, 58, 59, 2, 60, 61, 5, 62, 3, 22, 11, 63, 64, 65, 37, 66, 1, 67, 38, 12, 9, 68, 69, 5, 12, 70, 8, 1, 71, 4, 1, 72, 23, 13, 4, 1, 73, 12, 74, 39, 14, 40, 75, 76, 7, 15, 77, 24, 36, 2, 78, 1, 79, 7, 80, 11, 1, 81, 4, 1, 41, 2, 25, 13, 82, 16, 1, 20, 4, 42, 83, 3, 84, 85, 4, 26, 86, 9, 87, 27, 7, 28, 88, 29, 24, 89, 43, 2, 90, 17, 44, 3, 91, 2, 92, 26, 45, 18, 30, 1, 44, 93, 94, 4, 10, 46, 1, 95, 96, 2, 47, 16, 97, 6, 3, 45, 98, 7, 33, 8, 16, 3, 17, 48, 2, 31, 7, 99, 17, 100, 101, 2, 102, 2, 8, 103, 104, 1, 105, 106, 1, 107, 2, 108, 1, 20, 4, 109, 31, 110, 12, 42, 1, 111, 4, 16, 112, 5, 15, 14, 113, 18, 9, 114, 115, 2, 5, 116, 30, 117, 118, 119, 19, 12, 120, 29, 9, 121, 122, 2, 15, 9, 123, 29, 17, 124, 18, 19, 15, 125, 126, 11, 1, 127, 2, 31, 28, 128, 129, 130, 11, 1, 131, 132, 11, 9, 133, 134, 38, 7, 135, 34, 46, 30, 19, 136, 10, 137, 2, 49, 19, 47, 6, 138, 32, 3, 22, 10, 139, 27, 140, 27, 6, 141, 3

In [5]:
word_sequence=[]
for i in range(1,len(encoded_data)):
    sequence=encoded_data[i-1:i+1]
    word_sequence.append(sequence)
word_sequence=np.array(word_sequence)

In [6]:
print(word_sequence)

[[  5  33]
 [ 33  34]
 [ 34  50]
 [ 50   3]
 [  3   1]
 [  1  35]
 [ 35   8]
 [  8  51]
 [ 51   1]
 [  1  20]
 [ 20   4]
 [  4  52]
 [ 52  13]
 [ 13   5]
 [  5  53]
 [ 53  54]
 [ 54  55]
 [ 55  21]
 [ 21  36]
 [ 36   3]
 [  3   1]
 [  1  56]
 [ 56  57]
 [ 57   1]
 [  1  58]
 [ 58  59]
 [ 59   2]
 [  2  60]
 [ 60  61]
 [ 61   5]
 [  5  62]
 [ 62   3]
 [  3  22]
 [ 22  11]
 [ 11  63]
 [ 63  64]
 [ 64  65]
 [ 65  37]
 [ 37  66]
 [ 66   1]
 [  1  67]
 [ 67  38]
 [ 38  12]
 [ 12   9]
 [  9  68]
 [ 68  69]
 [ 69   5]
 [  5  12]
 [ 12  70]
 [ 70   8]
 [  8   1]
 [  1  71]
 [ 71   4]
 [  4   1]
 [  1  72]
 [ 72  23]
 [ 23  13]
 [ 13   4]
 [  4   1]
 [  1  73]
 [ 73  12]
 [ 12  74]
 [ 74  39]
 [ 39  14]
 [ 14  40]
 [ 40  75]
 [ 75  76]
 [ 76   7]
 [  7  15]
 [ 15  77]
 [ 77  24]
 [ 24  36]
 [ 36   2]
 [  2  78]
 [ 78   1]
 [  1  79]
 [ 79   7]
 [  7  80]
 [ 80  11]
 [ 11   1]
 [  1  81]
 [ 81   4]
 [  4   1]
 [  1  41]
 [ 41   2]
 [  2  25]
 [ 25  13]
 [ 13  82]
 [ 82  16]
 [ 16   1]
 [  1  20]

In [7]:
X=word_sequence[:,0]
Y=word_sequence[:,1]

In [8]:
print("X:",X)
print("Y:",Y)

X: [  5  33  34  50   3   1  35   8  51   1  20   4  52  13   5  53  54  55
  21  36   3   1  56  57   1  58  59   2  60  61   5  62   3  22  11  63
  64  65  37  66   1  67  38  12   9  68  69   5  12  70   8   1  71   4
   1  72  23  13   4   1  73  12  74  39  14  40  75  76   7  15  77  24
  36   2  78   1  79   7  80  11   1  81   4   1  41   2  25  13  82  16
   1  20   4  42  83   3  84  85   4  26  86   9  87  27   7  28  88  29
  24  89  43   2  90  17  44   3  91   2  92  26  45  18  30   1  44  93
  94   4  10  46   1  95  96   2  47  16  97   6   3  45  98   7  33   8
  16   3  17  48   2  31   7  99  17 100 101   2 102   2   8 103 104   1
 105 106   1 107   2 108   1  20   4 109  31 110  12  42   1 111   4  16
 112   5  15  14 113  18   9 114 115   2   5 116  30 117 118 119  19  12
 120  29   9 121 122   2  15   9 123  29  17 124  18  19  15 125 126  11
   1 127   2  31  28 128 129 130  11   1 131 132  11   9 133 134  38   7
 135  34  46  30  19 136  10 137   2  49  19  47

In [9]:
Y=np_utils.to_categorical(Y,num_classes=181)

In [10]:
print("Y:\n",Y)            #encoded o/p

Y:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
model=Sequential()
model.add(Embedding(input_dim=181,output_dim=20))
model.add(LSTM(100))
model.add(Dense(181,activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 20)          3620      
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               48400     
_________________________________________________________________
dense_1 (Dense)              (None, 181)               18281     
Total params: 70,301
Trainable params: 70,301
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(X,Y,epochs=300,verbose=1)


Epoch 1/300
354/354 [==============================] - 1s 3ms/step - loss: 5.1974 - accuracy: 0.0537
Epoch 2/300
354/354 [==============================] - 0s 118us/step - loss: 5.1893 - accuracy: 0.0932
Epoch 3/300
354/354 [==============================] - 0s 118us/step - loss: 5.1816 - accuracy: 0.0904
Epoch 4/300
354/354 [==============================] - 0s 118us/step - loss: 5.1718 - accuracy: 0.0847
Epoch 5/300
354/354 [==============================] - 0s 127us/step - loss: 5.1595 - accuracy: 0.0819
Epoch 6/300
354/354 [==============================] - 0s 124us/step - loss: 5.1424 - accuracy: 0.0819
Epoch 7/300
354/354 [==============================] - 0s 118us/step - loss: 5.1183 - accuracy: 0.0819
Epoch 8/300
354/354 [==============================] - 0s 118us/step - loss: 5.0870 - accuracy: 0.0819
Epoch 9/300
354/354 [==============================] - 0s 116us/step - loss: 5.0437 - accuracy: 0.0847
Epoch 10/300
354/354 [==============================] - 0s 121us/step - lo

354/354 [==============================] - 0s 121us/step - loss: 1.8436 - accuracy: 0.5226
Epoch 78/300
354/354 [==============================] - 0s 121us/step - loss: 1.8193 - accuracy: 0.5226
Epoch 79/300
354/354 [==============================] - 0s 118us/step - loss: 1.7954 - accuracy: 0.5282
Epoch 80/300
354/354 [==============================] - 0s 107us/step - loss: 1.7739 - accuracy: 0.5339
Epoch 81/300
354/354 [==============================] - 0s 113us/step - loss: 1.7535 - accuracy: 0.5282
Epoch 82/300
354/354 [==============================] - 0s 132us/step - loss: 1.7354 - accuracy: 0.5339
Epoch 83/300
354/354 [==============================] - 0s 116us/step - loss: 1.7159 - accuracy: 0.5424
Epoch 84/300
354/354 [==============================] - 0s 113us/step - loss: 1.6955 - accuracy: 0.5452
Epoch 85/300
354/354 [==============================] - 0s 107us/step - loss: 1.6758 - accuracy: 0.5395
Epoch 86/300
354/354 [==============================] - 0s 110us/step - loss:

354/354 [==============================] - 0s 121us/step - loss: 1.1884 - accuracy: 0.5452
Epoch 156/300
354/354 [==============================] - 0s 113us/step - loss: 1.1884 - accuracy: 0.5311
Epoch 157/300
354/354 [==============================] - 0s 118us/step - loss: 1.1857 - accuracy: 0.5339
Epoch 158/300
354/354 [==============================] - 0s 113us/step - loss: 1.1845 - accuracy: 0.5254
Epoch 159/300
354/354 [==============================] - 0s 121us/step - loss: 1.1815 - accuracy: 0.5339
Epoch 160/300
354/354 [==============================] - 0s 118us/step - loss: 1.1820 - accuracy: 0.5254
Epoch 161/300
354/354 [==============================] - 0s 118us/step - loss: 1.1787 - accuracy: 0.5141
Epoch 162/300
354/354 [==============================] - 0s 127us/step - loss: 1.1763 - accuracy: 0.5226
Epoch 163/300
354/354 [==============================] - 0s 121us/step - loss: 1.1740 - accuracy: 0.5113
Epoch 164/300
354/354 [==============================] - 0s 113us/ste

354/354 [==============================] - 0s 121us/step - loss: 1.1314 - accuracy: 0.5113
Epoch 234/300
354/354 [==============================] - 0s 121us/step - loss: 1.1339 - accuracy: 0.5282
Epoch 235/300
354/354 [==============================] - 0s 118us/step - loss: 1.1334 - accuracy: 0.5113
Epoch 236/300
354/354 [==============================] - 0s 121us/step - loss: 1.1347 - accuracy: 0.5169
Epoch 237/300
354/354 [==============================] - 0s 121us/step - loss: 1.1347 - accuracy: 0.5198
Epoch 238/300
354/354 [==============================] - 0s 121us/step - loss: 1.1321 - accuracy: 0.5198
Epoch 239/300
354/354 [==============================] - 0s 118us/step - loss: 1.1320 - accuracy: 0.5169
Epoch 240/300
354/354 [==============================] - 0s 113us/step - loss: 1.1302 - accuracy: 0.5169
Epoch 241/300
354/354 [==============================] - 0s 124us/step - loss: 1.1265 - accuracy: 0.5311
Epoch 242/300
354/354 [==============================] - 0s 121us/ste

In [14]:
word=input("enter word:")
no_of_next=int(input("enter no. of words you wanna predict:"))
in_word,next_word=word,word
for i in range(no_of_next):
    print(f"prediction:{i+1}")
    out_word=""
    encoded_test=tokenizer.texts_to_sequences([in_word])[0]
    encoded_test=np.array(encoded_test)
    pred=model.predict_classes(encoded_test,verbose=0)
    for word,index in tokenizer.word_index.items():
        if pred == index:
            out_word=word
            break
    in_word=out_word
    print(f"next word is:{out_word}")

enter word:then
enter no. of words you wanna predict:7
prediction:1
next word is:deny
prediction:2
next word is:my
prediction:3
next word is:request
prediction:4
next word is:but
prediction:5
next word is:at
prediction:6
next word is:home
prediction:7
next word is:and
